workspace:
  base: /go
  path: src/github.com/zottelchin/Mensa-Ingo

pipeline:
  build:
    image: golang
    commands:
    - CGO_ENABLED=1 GOOS=linux go build -a -ldflags '-extldflags "-static" -s' -installsuffix cgo -o Mensa-Ingo -v .

  publish:
    image: plugins/docker
    repo: zottelchin/Mensa-Ingo
    tags: latest
    dockerfile: Dockerfile-CI
    secrets: [ docker_username, docker_password ]
    when:
      branch: master